# Generated by Django 5.1.6 on 2025-02-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_unique_id_number_customuser_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterprofile',
            name='voter_id',
        ),
    ]
