# Generated by Django 5.1.6 on 2025-02-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_voterprofile_voter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voterprofile',
            old_name='user',
            new_name='voter',
        ),
    ]
